# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sysUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 430, 741, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_address = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_address.setGeometry(QtCore.QRect(60, 30, 341, 31))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 119, 381, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_webConfirm = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_webConfirm.setObjectName("btn_webConfirm")
        self.gridLayout.addWidget(self.btn_webConfirm, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_time = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_time.setGeometry(QtCore.QRect(100, 70, 151, 31))
        self.lineEdit_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(260, 80, 91, 16))
        self.label_4.setObjectName("label_4")
        self.btn_timeSet = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_timeSet.setGeometry(QtCore.QRect(280, 70, 121, 30))
        self.btn_timeSet.setObjectName("btn_timeSet")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(440, 40, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit_phoneNum = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_phoneNum.setGeometry(QtCore.QRect(520, 30, 211, 31))
        self.lineEdit_phoneNum.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_phoneNum.setObjectName("lineEdit_phoneNum")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(440, 70, 291, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_setphoneNum = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_setphoneNum.sizePolicy().hasHeightForWidth())
        self.btn_setphoneNum.setSizePolicy(sizePolicy)
        self.btn_setphoneNum.setObjectName("btn_setphoneNum")
        self.horizontalLayout.addWidget(self.btn_setphoneNum)
        self.btn_phoneTest = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_phoneTest.sizePolicy().hasHeightForWidth())
        self.btn_phoneTest.setSizePolicy(sizePolicy)
        self.btn_phoneTest.setObjectName("btn_phoneTest")
        self.horizontalLayout.addWidget(self.btn_phoneTest)
        self.lineEdit_Keyword = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Keyword.setGeometry(QtCore.QRect(520, 120, 113, 31))
        self.lineEdit_Keyword.setText("")
        self.lineEdit_Keyword.setObjectName("lineEdit_Keyword")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(440, 130, 72, 15))
        self.label_5.setObjectName("label_5")
        self.btn_kwedit = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_kwedit.setGeometry(QtCore.QRect(640, 120, 91, 30))
        self.btn_kwedit.setObjectName("btn_kwedit")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 721, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_start = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        self.view_console = QtWidgets.QTextEdit(self.centralwidget)
        self.view_console.setEnabled(True)
        self.view_console.setGeometry(QtCore.QRect(20, 10, 741, 411))
        self.view_console.setInputMethodHints(QtCore.Qt.ImhNone)
        self.view_console.setReadOnly(True)
        self.view_console.setObjectName("view_console")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "官网动态通知获取程序，开学日期提醒"))
        self.groupBox_2.setTitle(_translate("MainWindow", "操作面板"))
        self.label_2.setText(_translate("MainWindow", "网址："))
        self.btn_webConfirm.setText(_translate("MainWindow", "确认网址"))
        self.label_3.setText(_translate("MainWindow", "间隔时间："))
        self.lineEdit_time.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "S"))
        self.btn_timeSet.setText(_translate("MainWindow", "设置间隔时间"))
        self.label.setText(_translate("MainWindow", "手机号："))
        self.btn_setphoneNum.setText(_translate("MainWindow", "确定设置"))
        self.btn_phoneTest.setText(_translate("MainWindow", "测试一下"))
        self.label_5.setText(_translate("MainWindow", "关键词："))
        self.btn_kwedit.setText(_translate("MainWindow", "修改"))
        self.btn_start.setText(_translate("MainWindow", "开始  Start"))
        self.btn_stop.setText(_translate("MainWindow", "停止  Stop"))

